### ISSUE TITLE
Extract the autocmd function to be callable

### ISSUE THREAD

**Issue by Invertisment** [cvigilv/esqueleto.nvim#2]
What do you think about extracting the autocmd function to be able to run it manually?
I think this is not much work. 

This can be done using `nvim.create_user_command`. Then you could call the fill-in function from command menu.

**Comment by cvigilv** [comment]
By default, an autocommand is created when running `require("esqueleto").setup({})`, but this autocommand calls to a function called `insert` that does all the handling.

You could call this function as follows in order to use `esqueleto` on-demand:

~~~lua
require('esqueleto').insert("*.py")         -- file extension matching
require('esqueleto').insert("README.md")    -- file name matching
~~~

Now that you mention it, maybe it could be helpful to have the option to disable the creation of the autocommand by default in order to use `esqueleto` only on-demand. I will add it to the plugin roadmap.

**Comment by Invertisment** [comment]
> in order to use esqueleto only on-demand

That means that you won't really need to match the filetypes on you own :thinking: 
So the config would be "out of the box" according to the filetype found in `&filetype`

**Comment by cvigilv** [comment]
Yes and no. 

The premise of the plugin is to create an extensible, modular template manager. This means that the experience out-of-box should be good enough to use it without really investing heavy amounts of time configuring it, but you can also dive in and configure the behavior of the template selection and insertion as you wish. 

`esqueleto` is basically in its minimum viable product stage, the plan is to make it better as time goes on. I use templates a lot, so I want to make this process as streamlined and feature-rich as possible without going overboard.

**Comment by cvigilv** [comment]
I will implement an option to create the autocommand at `setup`. This way, you can choose to either (1) use it as intended or (2) on-demand.
I will create some user commands also to make the calling on-demand of `esqueleto` a little easier.

What do you think of:

~~~vim
Esqueleto            # matches filename then filetype by default
Esqueleto <pattern>  # matches the given pattern
~~~

**Comment by Invertisment** [comment]
For me anything works. I'm thinking whether I should use a snippet plugin but I have to trigger that one manually.
But with auto command I could trigger it when the opened buffer is empty too :thinking: 

And that could solve the issue when NvimTree opens a new buffer and it's empty.

**Comment by cvigilv** [comment]
#1 is going to solve the problem with empty buffers. I'm adding an option to enable `esqueleto` to run in empty buffers not created by Neovim. So that should be solved briefly.
