### ISSUE TITLE
feat(template):  insert method `vim.snippet.expand` instead `nvim_buf_set_lines`

### ISSUE THREAD

**Issue by AgatZan** [cvigilv/esqueleto.nvim#57]
There is a snippet API for inserting templates, which will allow you to add a little more freedom to create skeletons, since it will rely on the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax)

Usage example:
- multi-tabstop `$1`, `$2`...
- variable transform. `${TM_FILENAME/[\\.]/_/}` to `example-123_456-TEST.js` Replace the first . with _

**Comment by cvigilv** [comment]
This is a nice idea but defeats the purpose of templating (imho). I thought of it when i started developing this plugin, but decided going against it since it would mean I could simply have a snippets manager with the complete template inside it. I prefer having templates and snippets separated, as they can be involved in different things and have different workflows.

The idea of having variable transformation is interesting, I could look into implementing that.

**Comment by cvigilv** [comment]
Closing since I won't implement this
